language: python
addons:
- firefox: latest
python:
- 3.7.4
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- coverage run manage.py test
after_success:
- coveralls
deploy:
  provider: heroku:git
  api_key:
    secure: Code execution.
  edge: true
  app: am-tdd-tutorial
  on: AM_ICTRAINING-787_TDD_tutorial